resources:
- cert-manager.yaml
#- clusterissuer-letsencrypt-prod.yaml
patches:
  - path: cm-default-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
      